$.Redactor.opts.langs['fr'] = {
		"html": 'HTML',
		"video": 'Insérer une vidéo',
		"image": 'Insérer une image',
		"table": 'Tableau',
		"link": 'Lien',
		"link_insert": 'Insérer un lien',
		"link_edit": 'Editer le lien',
		"unlink": 'Supprimer le lien',
		"formatting": 'Formatage',
		"paragraph": 'Texte normal',
		"quote": 'Citation',
		"code": 'Code',
		"header1": 'Titre 1',
		"header2": 'Titre 2',
		"header3": 'Titre 3',
		"header4": 'Titre 4',
		"header5": 'Titre 5',
		"bold": 'Gras',
		"italic": 'Italique',
		"fontcolor": 'Couleur du texte',
		"backcolor": 'Couleur de fond',
		"unorderedlist": 'Liste non ordonnée',
		"orderedlist": 'Liste',
		"outdent": 'Retrait à gauche',
		"indent": 'Retrait à droite',
		"cancel": 'Annuler',
		"insert": 'Insérer',
		"save": 'Enregistrer',
		"_delete": 'Supprimer',
		"insert_table": 'Insérer un tableau',
		"insert_row_above": 'Ajouter une ligne au dessus',
		"insert_row_below": 'Ajouter une ligne en dessous',
		"insert_column_left": 'Ajouter une colonne à gauche',
		"insert_column_right": 'Ajouter une colonne à droite',
		"delete_column": 'Supprimer une colonne',
		"delete_row": 'Supprimer la ligne',
		"delete_table": 'Supprimer le tableau',
		"rows": 'Ligne',
		"columns": 'Colonne',
		"add_head": 'Ajouter entête',
		"delete_head": 'Supprimer entête',
		"title": 'Titre',
		"image_position": 'Position',
		"none": 'Aucune',
		"left": 'Gauche',
		"right": 'Droite',
		"center": 'Centre',
		"image_web_link": 'Lien de l\'image',
		"text": 'Texte',
		"mailto": 'Email',
		"web": 'URL',
		"video_html_code": 'Lien vers la vidéo (Youtube/Vimeo)',
		"file": 'Insérer un fichier',
		"upload": 'Envoyer',
		"download": 'Télécharger',
		"choose": 'Choisir',
		"or_choose": 'Ou choisir',
		"drop_file_here": 'Déposer un fichier ici',
		"align_left": 'Aligner le texte à gauche',
		"align_center": 'Centrer le texte',
		"align_right": 'Aligner le texte à droite',
		"align_justify": 'Justifier le texte',
		"horizontalrule": 'Insérer une ligne horizontale',
		"deleted": 'Barrer',
		"anchor": 'Ancre',
		"link_new_tab": 'Ouvrir le lien dans un nouvel onglet',
		"underline": 'Souligner',
		"alignment": 'Alignement',
		"filename": 'Nom (optionnel)',
		"edit": 'Editer',
		"upload_label": 'Déposer un fichier ici ou '
	};
